#! /bin/sh
if [ "x$1" = "x" ]
then
	echo "Usage: $0 <release number>"
	exit 1
fi

autoconf
if test -e Makefile; then
  make devclean
fi

PWDSAVE=`pwd`
PACKAGE=`basename $PWDSAVE`
pushd ..
ln -s $PACKAGE $PACKAGE-$1
tar zhcvf $PWDSAVE/SOURCES/$PACKAGE-$1.tar.gz --exclude RCS --exclude CVS --exclude SOURCES --exclude RPMS --exclude SRPMS --exclude redhat --exclude debian --exclude solaris --exclude sparc64 --exclude rpmrc --exclude rpmmacros --exclude *~ --exclude .#* $PACKAGE-$1
rm $PACKAGE-$1
popd

gzip -cd SOURCES/$PACKAGE-$1.tar.gz | bzip2 -c9 > SOURCES/$PACKAGE-$1.tar.bz2

if md5sum --help >/dev/null; then
	md5sum ./SOURCES/$PACKAGE-$1.tar.gz > ./SOURCES/$PACKAGE-$1.tar.gz.md5
	md5sum ./SOURCES/$PACKAGE-$1.tar.bz2 > ./SOURCES/$PACKAGE-$1.tar.bz2.md5
fi
