#!/bin/bash

set -xeu

temp=$(mktemp -d)
trap "cd $HOME; rm -rf $temp; exit 1" EXIT
curl -sS http://nagiosplug.sourceforge.net/snapshot/nagios-plugins-HEAD.tar.gz|tar -C "$temp" --strip-components=1 -xzf -
cd $temp
./configure && make
$HOME/bin/update_man_pages

