#! /bin/bash
# sfwebcron

# To update the developers-guidelines.html and put in html area
#
# Install in cron with something like:
#  47 7 * * * $HOME/bin/sfwebcron >/tmp/sfwebcron.log 2>&1 || cat /tmp/sfwebcron.log

set -eu
trap 'echo "Command failed at line $LINENO"' ERR

# Set working variables
PROJECT=nagiosplug
IN=${HOME}/sfwebcron
OUT_SERVER="tonvoon@frs.sourceforge.net"
OUT_PATH="/home/groups/n/na/nagiosplug/htdocs"

if [[ ! -e developer-guidelines.html.last ]] ; then
	touch developer-guidelines.html.last
fi

# Get latest dev guildelines
[[ ! -d $IN ]] && mkdir $IN
cd $IN
if [[ ! -d nagios-plugins ]] ; then
	git clone https://github.com/nagios-plugins/nagios-plugins.git nagios-plugins
fi
cd nagios-plugins/doc
git pull

make
if [[ developer-guidelines.html -nt developer-guidelines.html.last ]] ; then
	rsync -av developer-guidelines.{html,sgml} $OUT_SERVER:$OUT_PATH/
	touch developer-guidelines.html.last
fi

